### ISSUE TITLE
В readme заменить БЕМ на БЭМ

### ISSUE THREAD

**Issue by arikon** [sullenor/teatime#7]
Блок — Элемент — Модификатор = БЭМ, не БЕМ.

Кроме того, что это фактическая ошибка, инструмент ещё и в поиске не найти по слову БЭМ ;)

**Comment by sullenor** [comment]
Да, спасибо за замечание, я английскую аббревиатуру транслитерировал неудачно :)

**Comment by mightyaleksey** [comment]
Готово!
https://github.com/sullenor/teatime/releases/tag/0.3.1
